/*
 * Coinbase Pro API
 *
 * The Coinbase Pro API. See https://docs.pro.coinbase.com/ for more details on rate limiting, sandbox mode, and more.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type FeeRateItem struct {
	MakerFeeRate string `json:"maker_fee_rate,omitempty"`
	TakerFeeRate string `json:"taker_fee_rate,omitempty"`
	UsdVolume string `json:"usd_volume,omitempty"`
}
