/*
 * Coinbase Pro API
 *
 * The Coinbase Pro API. See https://docs.pro.coinbase.com/ for more details on rate limiting, sandbox mode, and more.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Trade struct {
	Time string `json:"time,omitempty"`
	TradeId int32 `json:"trade_id,omitempty"`
	Price string `json:"price,omitempty"`
	Size string `json:"size,omitempty"`
	Side string `json:"side,omitempty"`
}
