/*
 * Coinbase Pro API
 *
 * The Coinbase Pro API. See https://docs.pro.coinbase.com/ for more details on rate limiting, sandbox mode, and more.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type LedgerItem struct {
	// ledger item id?
	Id string `json:"id,omitempty"`
	// timestamp as string
	CreatedAt string `json:"created_at,omitempty"`
	Amount string `json:"amount,omitempty"`
	Balance string `json:"balance,omitempty"`
	Type_ string `json:"type,omitempty"`
	Details *LedgerItemDetails `json:"details,omitempty"`
}
