/*
 * Coinbase Pro API
 *
 * The Coinbase Pro API. See https://docs.pro.coinbase.com/ for more details on rate limiting, sandbox mode, and more.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Hold struct {
	Id string `json:"id,omitempty"`
	AccountId string `json:"account_id,omitempty"`
	CreatedAt string `json:"created_at,omitempty"`
	UpdatedAt string `json:"updated_at,omitempty"`
	Amount string `json:"amount,omitempty"`
	Type_ string `json:"type,omitempty"`
	Reg string `json:"reg,omitempty"`
}
