/*
 * Coinbase Pro API
 *
 * The Coinbase Pro API. See https://docs.pro.coinbase.com/ for more details on rate limiting, sandbox mode, and more.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Candle struct {
	Time int32 `json:"time,omitempty"`
	Low float32 `json:"low,omitempty"`
	High float32 `json:"high,omitempty"`
	Open float32 `json:"open,omitempty"`
	Close float32 `json:"close,omitempty"`
	Volume float32 `json:"volume,omitempty"`
}
