/*
 * Coinbase Pro API
 *
 * The Coinbase Pro API. See https://docs.pro.coinbase.com/ for more details on rate limiting, sandbox mode, and more.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Ticker struct {
	TradeId int32 `json:"trade_id,omitempty"`
	Price string `json:"price,omitempty"`
	Size string `json:"size,omitempty"`
	Bid string `json:"bid,omitempty"`
	Ask string `json:"ask,omitempty"`
	Volume string `json:"volume,omitempty"`
	Time string `json:"time,omitempty"`
}
