/*
 * Coinbase Pro API
 *
 * The Coinbase Pro API. See https://docs.pro.coinbase.com/ for more details on rate limiting, sandbox mode, and more.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type WebhookChange struct {
	Type_ string `json:"type,omitempty"`
	Time string `json:"time,omitempty"`
	Sequence int32 `json:"sequence,omitempty"`
	OrderId string `json:"order_id,omitempty"`
	ProductId string `json:"product_id,omitempty"`
	Side string `json:"side,omitempty"`
	Price string `json:"price,omitempty"`
	NewSize string `json:"new_size,omitempty"`
	OldSize string `json:"old_size,omitempty"`
	NewFunds string `json:"new_funds,omitempty"`
	OldFunds string `json:"old_funds,omitempty"`
}
