/*
 * Coinbase Pro API
 *
 * The Coinbase Pro API. See https://docs.pro.coinbase.com/ for more details on rate limiting, sandbox mode, and more.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Conversion struct {
	Id string `json:"id,omitempty"`
	Amount string `json:"amount,omitempty"`
	FromAccountId string `json:"from_account_id,omitempty"`
	ToAccountId string `json:"to_account_id,omitempty"`
	From string `json:"from,omitempty"`
	To string `json:"to,omitempty"`
}
