/*
 * Coinbase Pro API
 *
 * The Coinbase Pro API. See https://docs.pro.coinbase.com/ for more details on rate limiting, sandbox mode, and more.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Account struct {
	// Account ID
	Id string `json:"id,omitempty"`
	// the currency of the account
	Currency string `json:"currency,omitempty"`
	// total funds in the account
	Balance string `json:"balance,omitempty"`
	// funds on hold (not available for use)
	Holds string `json:"holds,omitempty"`
	// funds available to withdraw or trade
	Available bool `json:"available,omitempty"`
	// is trading enabled for this account?
	TradingEnabled bool `json:"trading_enabled,omitempty"`
}
