/*
 * Coinbase Pro API
 *
 * The Coinbase Pro API. See https://docs.pro.coinbase.com/ for more details on rate limiting, sandbox mode, and more.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Product struct {
	Id string `json:"id,omitempty"`
	DisplayName string `json:"display_name,omitempty"`
	BaseCurrency string `json:"base_currency,omitempty"`
	QuoteCurrency string `json:"quote_currency,omitempty"`
	BaseIncrement string `json:"base_increment,omitempty"`
	QuoteIncrement string `json:"quote_increment,omitempty"`
	BaseMinSize string `json:"base_min_size,omitempty"`
	BaseMaxSize string `json:"base_max_size,omitempty"`
	MinMarketFunds string `json:"min_market_funds,omitempty"`
	MaxMarketFunds string `json:"max_market_funds,omitempty"`
	Status string `json:"status,omitempty"`
	StatusMessage string `json:"status_message,omitempty"`
	CancelOnly bool `json:"cancel_only,omitempty"`
	LimitOnly bool `json:"limit_only,omitempty"`
	PostOnly bool `json:"post_only,omitempty"`
	TradingDisabled bool `json:"trading_disabled,omitempty"`
}
