/*
 * Coinbase Pro API
 *
 * The Coinbase Pro API. See https://docs.pro.coinbase.com/ for more details on rate limiting, sandbox mode, and more.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Fill struct {
	TradeId int32 `json:"trade_id,omitempty"`
	ProductId string `json:"product_id,omitempty"`
	Price string `json:"price,omitempty"`
	Size string `json:"size,omitempty"`
	OrderId string `json:"order_id,omitempty"`
	CreatedAt string `json:"created_at,omitempty"`
	Liquidity string `json:"liquidity,omitempty"`
	Fee string `json:"fee,omitempty"`
	Settled bool `json:"settled,omitempty"`
	Side string `json:"side,omitempty"`
}
