/*
 * Coinbase Pro API
 *
 * The Coinbase Pro API. See https://docs.pro.coinbase.com/ for more details on rate limiting, sandbox mode, and more.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// One of size or funds is required.
type MarketOrderRequest struct {
	Size string `json:"size,omitempty"`
	Funds string `json:"funds,omitempty"`
}
