/*
 * Coinbase Pro API
 *
 * The Coinbase Pro API. See https://docs.pro.coinbase.com/ for more details on rate limiting, sandbox mode, and more.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type WebsocketSnapshot struct {
	Type_ string `json:"type,omitempty"`
	ProductId string `json:"product_id,omitempty"`
	Bids [][]string `json:"bids,omitempty"`
	Asks [][]string `json:"asks,omitempty"`
}
