/*
 * Coinbase Pro API
 *
 * The Coinbase Pro API. See https://docs.pro.coinbase.com/ for more details on rate limiting, sandbox mode, and more.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type WebsocketTicker struct {
	Type_ string `json:"type,omitempty"`
	TradeId int32 `json:"trade_id,omitempty"`
	Sequence int32 `json:"sequence,omitempty"`
	Time string `json:"time,omitempty"`
	ProductId string `json:"product_id,omitempty"`
	Price string `json:"price,omitempty"`
	Side string `json:"side,omitempty"`
	LastSize string `json:"last_size,omitempty"`
	BestBid string `json:"best_bid,omitempty"`
	BestAsk string `json:"best_ask,omitempty"`
}
