/*
 * Coinbase Pro API
 *
 * The Coinbase Pro API. See https://docs.pro.coinbase.com/ for more details on rate limiting, sandbox mode, and more.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Stats struct {
	Open string `json:"open,omitempty"`
	High string `json:"high,omitempty"`
	Low string `json:"low,omitempty"`
	Volume string `json:"volume,omitempty"`
	Last string `json:"last,omitempty"`
	Volume30day string `json:"volume_30day,omitempty"`
}
