/*
 * Coinbase Pro API
 *
 * The Coinbase Pro API. See https://docs.pro.coinbase.com/ for more details on rate limiting, sandbox mode, and more.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type LimitResponseItemBat struct {
	Max string `json:"max,omitempty"`
	Remaining string `json:"remaining,omitempty"`
	PeriodInDays int32 `json:"period_in_days,omitempty"`
}
