/*
 * Coinbase Pro API
 *
 * The Coinbase Pro API. See https://docs.pro.coinbase.com/ for more details on rate limiting, sandbox mode, and more.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type WebhookReceived struct {
	Type_ string `json:"type,omitempty"`
	Time string `json:"time,omitempty"`
	ProductId string `json:"product_id,omitempty"`
	Sequence int32 `json:"sequence,omitempty"`
	OrderId string `json:"order_id,omitempty"`
	Side string `json:"side,omitempty"`
	OrderType string `json:"order_type,omitempty"`
	Funds string `json:"funds,omitempty"`
	Size string `json:"size,omitempty"`
	Price string `json:"price,omitempty"`
}
