/*
 * Coinbase Pro API
 *
 * The Coinbase Pro API. See https://docs.pro.coinbase.com/ for more details on rate limiting, sandbox mode, and more.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type LimitResponseTransferLimits struct {
	Ach *LimitResponseItem `json:"ach,omitempty"`
	AchNoBalance *LimitResponseItem `json:"ach_no_balance,omitempty"`
	CreditDebitCard *LimitResponseItem `json:"credit_debit_card,omitempty"`
	AchCurm *LimitResponseItem `json:"ach_curm,omitempty"`
	Secure3dBuy *LimitResponseItem `json:"secure3d_buy,omitempty"`
	ExchangeWithdraw *LimitResponseItem `json:"exchange_withdraw,omitempty"`
	ExchangeAch *LimitResponseItem `json:"exchange_ach,omitempty"`
	PaypalWithdrawl *LimitResponseItem `json:"paypal_withdrawl,omitempty"`
	InstantAchWithdrawl *LimitResponseItem `json:"instant_ach_withdrawl,omitempty"`
	Buy *LimitResponseItem `json:"buy,omitempty"`
	Sell *LimitResponseItem `json:"sell,omitempty"`
}
