/*
 * Coinbase Pro API
 *
 * The Coinbase Pro API. See https://docs.pro.coinbase.com/ for more details on rate limiting, sandbox mode, and more.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type LimitResponse struct {
	LimitCurrency string `json:"limit_currency,omitempty"`
	TransferLimits *LimitResponseTransferLimits `json:"transfer_limits,omitempty"`
}
