/*
 * Coinbase Pro API
 *
 * The Coinbase Pro API. See https://docs.pro.coinbase.com/ for more details on rate limiting, sandbox mode, and more.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type WebsocketMatch struct {
	Type_ string `json:"type,omitempty"`
	TradeId int32 `json:"trade_id,omitempty"`
	Sequence int32 `json:"sequence,omitempty"`
	MakerOrderId string `json:"maker_order_id,omitempty"`
	TakerOrderId string `json:"taker_order_id,omitempty"`
	Time string `json:"time,omitempty"`
	ProductId string `json:"product_id,omitempty"`
	Size string `json:"size,omitempty"`
	Price string `json:"price,omitempty"`
	Side string `json:"side,omitempty"`
	TakerUserId string `json:"taker_user_id,omitempty"`
	UserId string `json:"user_id,omitempty"`
	TakerProfileId string `json:"taker_profile_id,omitempty"`
	ProfileId string `json:"profile_id,omitempty"`
}
