/*
 * Coinbase Pro API
 *
 * The Coinbase Pro API. See https://docs.pro.coinbase.com/ for more details on rate limiting, sandbox mode, and more.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type OrderRequest struct {
	// Order ID selected by you to identify your order
	ClientOid string `json:"client_oid,omitempty"`
	Type_ string `json:"type,omitempty"`
	Side string `json:"side,omitempty"`
	ProductId string `json:"product_id,omitempty"`
	// Self-trade prevention flag dc:  Decrease and Cancel (default) co:  Cancel oldest cn:  Cancel newest cb:  Cancel both 
	Stp string `json:"stp,omitempty"`
	Stop string `json:"stop,omitempty"`
	// Only if stop is defined. Sets trigger price for stop order.
	StopPrice string `json:"stop_price,omitempty"`
	Size string `json:"size,omitempty"`
	Price string `json:"price,omitempty"`
	TimeInForce string `json:"time_in_force,omitempty"`
	CancelAfter string `json:"cancel_after,omitempty"`
	PostOnly bool `json:"post_only,omitempty"`
	Funds string `json:"funds,omitempty"`
}
