/*
 * Coinbase Pro API
 *
 * The Coinbase Pro API. See https://docs.pro.coinbase.com/ for more details on rate limiting, sandbox mode, and more.
 *
 * API version: 2.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Order struct {
	Id string `json:"id,omitempty"`
	Price string `json:"price,omitempty"`
	Size string `json:"size,omitempty"`
	ProductId string `json:"product_id,omitempty"`
	Side string `json:"side,omitempty"`
	Stp string `json:"stp,omitempty"`
	Type_ string `json:"type,omitempty"`
	TimeInForce string `json:"time_in_force,omitempty"`
	PostOnly bool `json:"post_only,omitempty"`
	CreatedAt string `json:"created_at,omitempty"`
	FillFees string `json:"fill_fees,omitempty"`
	FilledSize string `json:"filled_size,omitempty"`
	ExecutedValue string `json:"executed_value,omitempty"`
	Status string `json:"status,omitempty"`
	Settled bool `json:"settled,omitempty"`
}
